# Re-Scaling and Normalization

In [4]:
import pandas as pd
Location = r'c:\C:\Users\Panu\GoogleDrive\01_DataScience\Datasets'

df = pd.read_csv('Diabetes.csv')
df.head()

Number of times pregnant   Plasma glucose concentration  \
0                          6                            148   
1                          1                             85   
2                          8                            183   
3                          1                             89   
4                          0                            137   

    Diastolic blood pressure   Triceps skin fold thickness  \
0                         72                            35   
1                         66                            29   
2                         64                             0   
3                         66                            23   
4                         40                            35   

    2-Hour serum insulin   Body mass index   Diabetes pedigree function  \
0                      0              33.6                        0.627   
1                      0              26.6                        0.351   
2                      0              23.3                        0.672   
3                     94              28.1                        0.167   
4                    168              43.1                        2.288   

    Age (years)  Class variable  
0            50             YES  
1            31              NO  
2            32             YES  
3            21              NO  
4            33             YES

In [6]:
X = array[:,0:8]
y = array[:,8]
#this is dependent

In [7]:
print(X)

[[6 148 72 ... 33.6 0.627 50]
 [1 85 66 ... 26.6 0.35100000000000003 31]
 [8 183 64 ... 23.3 0.672 32]
 ...
 [5 121 72 ... 26.2 0.245 30]
 [1 126 60 ... 30.1 0.349 47]
 [1 93 70 ... 30.4 0.315 23]]


# Rescaling (min-max normalization)
Also known as min-max scaling or min-max normalisation, is the simplest method and consists in rescaling the range of features to scale the range in [0, 1] or [−1, 1]. Selecting the target range depends on the nature of the data.

In [8]:
from sklearn.preprocessing import MinMaxScaler

In [9]:
scaler = MinMaxScaler(feature_range=(0,1))

Scaling Data between 0 and 1

In [10]:
rescaled = scaler.fit_transform(X)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype object was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


In [13]:
import numpy as np
np.set_printoptions(precision=3)

In [16]:
print(rescaled[0:5,:])

[[0.353 0.744 0.59  0.354 0.    0.501 0.234 0.483]
 [0.059 0.427 0.541 0.293 0.    0.396 0.117 0.167]
 [0.471 0.92  0.525 0.    0.    0.347 0.254 0.183]
 [0.059 0.447 0.541 0.232 0.111 0.419 0.038 0.   ]
 [0.    0.688 0.328 0.354 0.199 0.642 0.944 0.2  ]]


In [17]:
print(X)

[[6 148 72 ... 33.6 0.627 50]
 [1 85 66 ... 26.6 0.35100000000000003 31]
 [8 183 64 ... 23.3 0.672 32]
 ...
 [5 121 72 ... 26.2 0.245 30]
 [1 126 60 ... 30.1 0.349 47]
 [1 93 70 ... 30.4 0.315 23]]


# Standardization
In machine learning, we can handle various types of data, e.g. audio signals and pixel values for image data, and this data can include multiple dimensions. Feature standardization makes the values of each feature in the data have zero-mean (when subtracting the mean in the numerator) and unit-variance. This method is widely used for normalization in many machine learning algorithms (e.g., support vector machines, logistic regression, and artificial neural networks)[2][citation needed]. The general method of calculation is to determine the distribution mean and standard deviation for each feature. Next we subtract the mean from each feature. Then we divide the values (mean is already subtracted) of each feature by its standard deviation.

In [19]:
from sklearn.preprocessing import StandardScaler

In [21]:
scalar2 = StandardScaler()

In [22]:
rescaled2 = scalar2.fit_transform(X)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [23]:
print(rescaled2[0:5,:])

[[ 0.64   0.848  0.15   0.907 -0.693  0.204  0.468  1.426]
 [-0.845 -1.123 -0.161  0.531 -0.693 -0.684 -0.365 -0.191]
 [ 1.234  1.944 -0.264 -1.288 -0.693 -1.103  0.604 -0.106]
 [-0.845 -0.998 -0.161  0.155  0.123 -0.494 -0.921 -1.042]
 [-1.142  0.504 -1.505  0.907  0.766  1.41   5.485 -0.02 ]]


Values with a mean of 0 and Sd of 1
takes ea feature value
calculat the mean of ea feature
subtracts the mean
then div by sd
then we get this values
This is the 2nd pre-processing technique

# Normalizer

Normalization used when we have lot of 0 values, missing values
or attribute varying scale used in NNs ,KNNs
rescaling ea object to a length of 1 called unit norm in linear algorithm

In [27]:
from sklearn.preprocessing import Normalizer

In [28]:
scaler3 = Normalizer()

In [29]:
rescaled3 = scaler3.fit_transform(X)

In [30]:
print(rescaled3[0:5,:])

[[0.034 0.828 0.403 0.196 0.    0.188 0.004 0.28 ]
 [0.008 0.716 0.556 0.244 0.    0.224 0.003 0.261]
 [0.04  0.924 0.323 0.    0.    0.118 0.003 0.162]
 [0.007 0.588 0.436 0.152 0.622 0.186 0.001 0.139]
 [0.    0.596 0.174 0.152 0.731 0.188 0.01  0.144]]


# Binarizer Make Data binary

Set a threshold , anything above there is 1 or 0 and viceversa

In [31]:
from sklearn.preprocessing import Binarizer

In [32]:
scaler4 = Binarizer(threshold=0.0)

In [33]:
rescaled4 = scaler4.fit_transform(X)

In [34]:
print(rescaled4[0:5,:])

[[1. 1. 1. 1. 0. 1. 1. 1.]
 [1. 1. 1. 1. 0. 1. 1. 1.]
 [1. 1. 1. 0. 0. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1. 1. 1. 1.]]


# Feature Scaling Project

In [35]:
from sklearn.linear_model import Ridge

In [36]:
from sklearn.metrics import mean_squared_error,r2_score

In [37]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv"

In [38]:
df = pd.read_csv(url,sep=";")

In [39]:
df.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [40]:
y = df.quality

In [42]:
y.head()

0    5
1    5
2    5
3    6
4    5
Name: quality, dtype: int64

In [43]:
X = df.drop('quality',axis=1)

In [44]:
X.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  
0      9.4  
1      9.8  
2      9.8  
3      9.8  
4      9.4

In [46]:
test_size = 0.33
from sklearn.model_selection import  train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = test_size,random_state = 123, stratify=y)

for reproduceability,
stratified sampling

In [47]:
clf = Ridge()

In [48]:
clf.fit(X_train,y_train)

Ridge(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=None,
   normalize=False, random_state=None, solver='auto', tol=0.001)

In [49]:
prediction = clf.predict(X_test)

In [50]:
print(r2_score(y_test,prediction))

0.3327115369264244


In [51]:
print(mean_squared_error(y_test,prediction))

0.43175179697978205


In [52]:
scaler = StandardScaler()

In [53]:
X_train_scaled = scaler.fit_transform(X_train)

In [54]:
X_test_scaled = scaler.fit_transform(X_test)

In [55]:
clf2 = Ridge()

In [57]:
clf2.fit(X_train_scaled,y_train)

Ridge(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=None,
   normalize=False, random_state=None, solver='auto', tol=0.001)

In [58]:
prediction2 = clf2.predict(X_test_scaled)

In [59]:
print(r2_score(y_test,prediction2))

0.3321055767312402


In [60]:
print(mean_squared_error(y_test,prediction2))

0.43214386790209947


Slightly better